# Generated by Django 5.1.4 on 2025-03-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_entry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
